### ISSUE TITLE
General UI Layout (Colors + Fonts  + Rename)

### ISSUE THREAD

**Issue by thuyvyng** [thuyvyng/spotifyInteractive#1]
do we go cute bright or do we wanna do like gamer dark mode... hm

**Comment by thuyvyng** [comment]
cat visualization names:
- cat-ify your spotify
- spotify purrsona

**Comment by thuyvyng** [comment]
link color palettes:
- https://coolors.co/palette/f6bd60-f7ede2-f5cac3-84a59d-f28482
- https://coolors.co/palette/006d77-83c5be-edf6f9-ffddd2-e29578

**Comment by ruangroc** [comment]
I particularly like: 
* https://coolors.co/palette/f6bd60-f7ede2-f5cac3-84a59d-f28482
* https://www.canva.com/colors/color-palettes/bicycle-at-rest/
* https://coolors.co/palette/b09e99-fee9e1-fad4c0-64b6ac-c0fdfb

**Comment by thuyvyng** [comment]
[> I particularly like:
> 
> * https://coolors.co/palette/f6bd60-f7ede2-f5cac3-84a59d-f28482
> * https://www.canva.com/colors/color-palettes/bicycle-at-rest/
> * https://coolors.co/palette/b09e99-fee9e1-fad4c0-64b6ac-c0fdfb
](https://coolors.co/palette/f6bd60-f7ede2-f5cac3-84a59d-f28482)

**Comment by thuyvyng** [comment]
im gonna go w https://coolors.co/palette/f6bd60-f7ede2-f5cac3-84a59d-f28482 w the navy and maybe the grey from https://www.canva.com/colors/color-palettes/bicycle-at-rest/ for SOME dark colors

**Comment by thuyvyng** [comment]
<img width="1439" alt="Screen Shot 2023-01-11 at 4 11 13 PM" src="https://user-images.githubusercontent.com/43559792/211945333-35884f0a-b7d2-443c-b635-124843e04073.png">
<img width="1439" alt="Screen Shot 2023-01-11 at 4 13 19 PM" src="https://user-images.githubusercontent.com/43559792/211945337-bb0e5297-dbe6-44a1-94d0-b80f461277dc.png">

**Comment by ruangroc** [comment]
I think having a way for users to switch between light and dark mode would be cool if you think that's doable. Double color palette :)

**Comment by thuyvyng** [comment]
lol that will be extra feature
